//------------------------------------------------------------------------------
// <auto-generated>
// Well, not really. This is just a trick to get StyleCop off my back for this unique file.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
// Reasoning: Because this is a unique file.
namespace SpreadsheetApp
{
    [global::System.AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]

    public sealed class ViewModelAttribute : System.Attribute
    {
        public ViewModelAttribute() { }

        /// <summary>
        /// Activated Attribute.
        /// </summary>
        /// <param name="Activated">Pass in whether attribute is activated or not.</param>
        public ViewModelAttribute(bool Activated)
        {
            this.Activated = Activated;
        }

        public bool Activated { get; set; }

#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
    }
}
